server:
  port: 1112
spring.profiles.active: test
#配置服务命名，不区分大小写，在注册中心管理界面默认大写显示。
spring.application.name: service-ab#指定服务注册中心的地址
#eureka.client.service-url:
#  defaultZone: http://127.0.0.1:1111/eureka/

#健康检查 actuator 监控
management:
  #自定义web端口 -1 则关闭web管理
  server.port: 9999
  endpoints.web:
    #Spring Boot 2.0的端点基础路径由“/”调整到”/actuator”下,如：/info调整为/actuator/info
    #https://blog.csdn.net/alinyua/article/details/80009435
    base-path: /
    exposure:
      include: '*'
      #不包含这些端点
      exclude: env,beans,mappings

#模板配置
spring.thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML5
  encoding: UTF-8
  servlet:
    content-type: text/html
spring.jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
#redis 缓存配置 单节点
spring.redis:
  host: 192.168.31.108
  port: 6379
  database: 0
  password: 123456789
  timeout: 300
  jedis.pool:
    max-active: 1024
    max-wait: 60
    max-idle: 200
    min-idle: 0
#Mysql 及jpa配置
spring.datasource:
  #主库
  url: jdbc:mysql://192.168.31.108:3306/cloud-demo?characterEncoding=utf8&characterSetResults=utf8&useSSL=true&serverTimezone=GMT%2B8
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: selfflyer
  password: 'Selfflyer315#!%'
  type: com.alibaba.druid.pool.DruidDataSource
  #xa.data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
  #数据库连接池  可以使用 hikari
  dbcp2:
    #初始化连接数
    initial-size: 5
    #数据库最多维持连接
    max-idle: 5
    #数据库最少维持连接
    min-idle: 1
    #等待连接获取最大超时时间
    max-wait-millis: 200
    test-while-idle: true
    test-on-borrow: true
    test-on-return: true
    validation-query: SELECT 1
    remove-abandoned-timeout: 60
    log-abandoned: true
#spring jpa 相关配置
spring.jpa:
  database: MYSQL
  show-sql: true
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  hibernate:
    ddl-auto: create
    naming:
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy